[package]
name = "refactorign"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
peg = "0.8.4"
peg-runtime = "0.8.3"

[[bin]]
name = "refactorign"
path = "src/main.rs"
